export const EFFECTS = [
  { id: 'blur-suite', label: 'Blur', description: 'Multi-mode blur treatment' },
  { id: 'color-htone', label: 'C. Htone', description: 'Color halftone print pass' },
  { id: 'glassify', label: 'Glass', description: 'Prismatic ring refraction' },
  { id: 'ascii-kit', label: 'ASCII', description: 'Character-based rendering' },
  { id: 'image-track', label: 'Track', description: 'Ghost displacement trail' },
  { id: 'half-tone', label: 'Halftone', description: 'Dot matrix posterization' },
  { id: 'retroman', label: 'Dither', description: 'Ordered dithering pass' },
  { id: 'glitch-kit', label: 'Glitch', description: 'Chromatic corruption' },
  { id: 'vintage-kit', label: 'Vintage', description: 'Film emulation stack' },
  { id: 'img-track', label: 'ImgTrack', description: 'Region tracking and overlays' },
]

export const REGION_STYLES = [
  { id: 'basic', label: 'Basic' },
  { id: 'label', label: 'Label' },
  { id: 'frame', label: 'Frame' },
  { id: 'l-frame', label: 'L-Frame' },
  { id: 'x-frame', label: 'X-Frame' },
  { id: 'grid', label: 'Grid' },
  { id: 'particle', label: 'Particle' },
  { id: 'dash', label: 'Dash' },
  { id: 'scope', label: 'Scope' },
  { id: 'win2k', label: 'Win2K' },
  { id: 'label2', label: 'Label 2' },
]

export const REGION_FILTERS = [
  { id: 'none', label: 'None' },
  { id: 'inv', label: 'Inv' },
  { id: 'glitch', label: 'Glitch' },
  { id: 'thermal', label: 'Thermal' },
  { id: 'pixel', label: 'Pixel' },
  { id: 'tone', label: 'Tone' },
  { id: 'blur', label: 'Blur' },
  { id: 'dither', label: 'Dither' },
  { id: 'zoom', label: 'Zoom' },
  { id: 'xray', label: 'X-Ray' },
  { id: 'water', label: 'Water' },
  { id: 'mask', label: 'Mask' },
  { id: 'crt', label: 'CRT' },
  { id: 'edge', label: 'Edge' },
]

export const ASCII_CHARSETS = {
  dense: 'M@#W$9876543210?!abc;:+=-,._ ',
  classic: '@%#*+=-:. ',
  blocks: '█▓▒░ ',
  binary: '01 ',
  minimal: '#+-. ',
  retro: '░▒▓|/\\-=+. ',
}

export const DEFAULT_SETTINGS = {
  'blur-suite': {
    mode: 'linear',
    intensity: 20,
    grain: 0,
    rgbShift: 0,
    bloom: false,
    motionX: 0,
    motionY: 0,
    gradientMask: false,
    maskDirection: 0,
    maskSoftness: 40,
    maskPosition: 50,
    focusY: 50,
    focusWidth: 20,
    softness: 30,
    saturation: 0,
  },
  'color-htone': {
    colorMode: 'cmyk',
    dotSize: 8,
    mix: 100,
    brightness: 0,
    contrast: 0,
    background: '#ffffff',
    angle: 15,
  },
  glassify: {
    layers: 5,
    rotation: 0.15,
    radius: 100,
    shadowStrength: 40,
    shadowWidth: 2,
    highlightStrength: 30,
    highlightWidth: 1,
  },
  'ascii-kit': {
    renderMode: 'brightness',
    charset: 'dense',
    fontSize: 10,
    coverage: 100,
    edgeEmphasis: 60,
    bgMode: 'blurred',
    bgBlur: 14,
    bgOpacity: 100,
    colorMode: 'color',
    color: '#f7f7f2',
    charOpacity: 75,
    brightness: 0,
    contrast: 0,
    charBrightness: 0,
    charContrast: 0,
    invertMapping: false,
    dotGrid: false,
    animated: false,
    animSpeed: 1.5,
    animIntensity: 60,
    animRandomness: 50,
  },
  'image-track': {
    strength: 50,
  },
  'half-tone': {
    dotSize: 6,
    color: '#f7f7f2',
  },
  retroman: {
    scale: 2,
    color: '#f7f7f2',
  },
  'glitch-kit': {
    intensity: 50,
    colorShift: 10,
    scanlines: true,
  },
  'vintage-kit': {
    grain: 30,
    sepia: 80,
    vignette: 50,
  },
  'img-track': {},
}

export const EMPTY_REGION_STYLE = {
  shape: 'rectangle',
  style: 'basic',
  filter: 'none',
  connectionStyle: 'dashed',
  connectionRate: 55,
}
